import 'package:cloud_firestore/cloud_firestore.dart';

// ==========================================
// 1. EXAM MODEL
// ==========================================
class Exam {
  final String id;
  final String examCode; // Needed for students to join
  final String title;
  final String creatorName; // E.g., "Mr. John", "Bunda"
  final DateTime date;
  final DateTime startTime;
  final DateTime endTime;
  final int durationMinutes;
  final String securityPIN; // Emergency unlock PIN
  final bool isActive; 
  final String hostId; // Random ID stored in creator's device to verify ownership

  Exam({
    required this.id,
    required this.examCode,
    required this.title,
    required this.creatorName,
    required this.date,
    required this.startTime,
    required this.endTime,
    required this.durationMinutes,
    required this.securityPIN,
    required this.isActive,
    required this.hostId,
  });

  factory Exam.fromJson(Map<String, dynamic> json, String documentId) {
    return Exam(
      id: documentId,
      examCode: json['examCode'] ?? '',
      title: json['title'] ?? '',
      creatorName: json['creatorName'] ?? '',
      date: (json['date'] as Timestamp).toDate(),
      startTime: (json['startTime'] as Timestamp).toDate(),
      endTime: (json['endTime'] as Timestamp).toDate(),
      durationMinutes: json['durationMinutes'] ?? 0,
      securityPIN: json['securityPIN'] ?? '',
      isActive: json['isActive'] ?? false,
      hostId: json['hostId'] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'examCode': examCode,
      'title': title,
      'creatorName': creatorName,
      'date': Timestamp.fromDate(date),
      'startTime': Timestamp.fromDate(startTime),
      'endTime': Timestamp.fromDate(endTime),
      'durationMinutes': durationMinutes,
      'securityPIN': securityPIN,
      'isActive': isActive,
      'hostId': hostId,
    };
  }
}

// ==========================================
// 2. QUESTION MODEL (Remains the same)
// ==========================================
class Question {
  final String id;
  final String questionText;
  final List<String> options; 
  final int correctIndex; 
  final int order; 

  Question({
    required this.id,
    required this.questionText,
    required this.options,
    required this.correctIndex,
    required this.order,
  });

  factory Question.fromJson(Map<String, dynamic> json, String documentId) {
    return Question(
      id: documentId,
      questionText: json['questionText'] ?? '',
      options: List<String>.from(json['options'] ?? []),
      correctIndex: json['correctIndex'] ?? 0,
      order: json['order'] ?? 0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'questionText': questionText,
      'options': options,
      'correctIndex': correctIndex,
      'order': order,
    };
  }
}

// ==========================================
// 3. SUBMISSION MODEL
// ==========================================
class Submission {
  final String id; // Random Document ID generated by Firestore
  final String studentName; // Input from student
  final Map<String, int> answers; 
  final double score; 
  final DateTime submittedAt;
  final String status; 

  Submission({
    required this.id,
    required this.studentName,
    required this.answers,
    required this.score,
    required this.submittedAt,
    required this.status,
  });

  factory Submission.fromJson(Map<String, dynamic> json, String documentId) {
    return Submission(
      id: documentId,
      studentName: json['studentName'] ?? 'Unknown',
      answers: Map<String, int>.from(json['answers'] ?? {}),
      score: (json['score'] ?? 0).toDouble(),
      submittedAt: json['submittedAt'] != null 
          ? (json['submittedAt'] as Timestamp).toDate() 
          : DateTime.now(),
      status: json['status'] ?? 'in_progress',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'studentName': studentName,
      'answers': answers,
      'score': score,
      'submittedAt': Timestamp.fromDate(submittedAt), 
      'status': status,
    };
  }
}